[2022-05-01 20:04:27,226] {taskinstance.py:1031} INFO - Dependencies not met for <TaskInstance: cso_2295_ipo_2_cso.py.log_sensor2 scheduled__2022-04-28T15:41:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2022-05-01 20:04:27,299] {local_task_job.py:99} INFO - Task is not able to be run
