[2022-04-07 13:49:23,958] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag.create_pet_table manual__2022-04-07T13:49:22.844358+00:00 [queued]>
[2022-04-07 13:49:23,966] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag.create_pet_table manual__2022-04-07T13:49:22.844358+00:00 [queued]>
[2022-04-07 13:49:23,966] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 13:49:23,966] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-04-07 13:49:23,966] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 13:49:23,976] {taskinstance.py:1264} INFO - Executing <Task(PostgresOperator): create_pet_table> on 2022-04-07 13:49:22.844358+00:00
[2022-04-07 13:49:23,980] {standard_task_runner.py:52} INFO - Started process 1671 to run task
[2022-04-07 13:49:23,982] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'postgres_operator_dag', 'create_pet_table', 'manual__2022-04-07T13:49:22.844358+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/example_postgres.py', '--cfg-path', '/tmp/tmpjom4wxdq', '--error-file', '/tmp/tmpp6rfdhcy']
[2022-04-07 13:49:23,983] {standard_task_runner.py:77} INFO - Job 84: Subtask create_pet_table
[2022-04-07 13:49:24,031] {logging_mixin.py:109} INFO - Running <TaskInstance: postgres_operator_dag.create_pet_table manual__2022-04-07T13:49:22.844358+00:00 [running]> on host d73239f69a26
[2022-04-07 13:49:24,066] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_operator_dag
AIRFLOW_CTX_TASK_ID=create_pet_table
AIRFLOW_CTX_EXECUTION_DATE=2022-04-07T13:49:22.844358+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-07T13:49:22.844358+00:00
[2022-04-07 13:49:24,072] {base.py:79} INFO - Using connection to: id: postgres_default. Host: postgres, Port: 5432, Schema: ***, Login: ***, Password: ***, extra: {}
[2022-04-07 13:49:24,075] {dbapi.py:225} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS pet (
            pet_id SERIAL PRIMARY KEY,
            name VARCHAR NOT NULL,
            pet_type VARCHAR NOT NULL,
            birth_date DATE NOT NULL,
            OWNER VARCHAR NOT NULL);
          , parameters: None
[2022-04-07 13:49:24,075] {postgres.py:73} INFO - NOTICE:  relation "pet" already exists, skipping

[2022-04-07 13:49:24,083] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=postgres_operator_dag, task_id=create_pet_table, execution_date=20220407T134922, start_date=20220407T134923, end_date=20220407T134924
[2022-04-07 13:49:24,114] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-07 13:49:24,138] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
