[2022-04-07 13:51:48,145] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag.create_pet_table manual__2022-04-07T13:51:47.127693+00:00 [queued]>
[2022-04-07 13:51:48,153] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: postgres_operator_dag.create_pet_table manual__2022-04-07T13:51:47.127693+00:00 [queued]>
[2022-04-07 13:51:48,153] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 13:51:48,153] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-04-07 13:51:48,153] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 13:51:48,179] {taskinstance.py:1264} INFO - Executing <Task(PostgresOperator): create_pet_table> on 2022-04-07 13:51:47.127693+00:00
[2022-04-07 13:51:48,184] {standard_task_runner.py:52} INFO - Started process 1799 to run task
[2022-04-07 13:51:48,186] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'postgres_operator_dag', 'create_pet_table', 'manual__2022-04-07T13:51:47.127693+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/example_postgres.py', '--cfg-path', '/tmp/tmpujdlwh_e', '--error-file', '/tmp/tmp8v0wkjxp']
[2022-04-07 13:51:48,187] {standard_task_runner.py:77} INFO - Job 87: Subtask create_pet_table
[2022-04-07 13:51:48,224] {logging_mixin.py:109} INFO - Running <TaskInstance: postgres_operator_dag.create_pet_table manual__2022-04-07T13:51:47.127693+00:00 [running]> on host d73239f69a26
[2022-04-07 13:51:48,298] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_operator_dag
AIRFLOW_CTX_TASK_ID=create_pet_table
AIRFLOW_CTX_EXECUTION_DATE=2022-04-07T13:51:47.127693+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-07T13:51:47.127693+00:00
[2022-04-07 13:51:48,305] {base.py:79} INFO - Using connection to: id: postgres_default. Host: postgres, Port: 5432, Schema: ***, Login: ***, Password: ***, extra: {}
[2022-04-07 13:51:48,308] {dbapi.py:225} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS pet (
            pet_id SERIAL PRIMARY KEY,
            name VARCHAR NOT NULL,
            pet_type VARCHAR NOT NULL,
            birth_date DATE NOT NULL,
            OWNER VARCHAR NOT NULL);
          , parameters: None
[2022-04-07 13:51:48,309] {postgres.py:73} INFO - NOTICE:  relation "pet" already exists, skipping

[2022-04-07 13:51:48,318] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=postgres_operator_dag, task_id=create_pet_table, execution_date=20220407T135147, start_date=20220407T135148, end_date=20220407T135148
[2022-04-07 13:51:48,358] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-07 13:51:48,384] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
