[2022-04-21 21:34:56,636] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: cso_2295_ipo_2_cso.py.transfer_cso_pers manual__2022-04-21T21:31:39.420323+00:00 [queued]>
[2022-04-21 21:34:56,646] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: cso_2295_ipo_2_cso.py.transfer_cso_pers manual__2022-04-21T21:31:39.420323+00:00 [queued]>
[2022-04-21 21:34:56,647] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-04-21 21:34:56,647] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-04-21 21:34:56,647] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-04-21 21:34:56,656] {taskinstance.py:1264} INFO - Executing <Task(Postgres2File): transfer_cso_pers> on 2022-04-21 21:31:39.420323+00:00
[2022-04-21 21:34:56,661] {standard_task_runner.py:52} INFO - Started process 35798 to run task
[2022-04-21 21:34:56,664] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cso_2295_ipo_2_cso.py', 'transfer_cso_pers', 'manual__2022-04-21T21:31:39.420323+00:00', '--job-id', '946', '--raw', '--subdir', 'DAGS_FOLDER/cso_2295/cso_2295_ipo_2_cso.py', '--cfg-path', '/tmp/tmpmkzt2s8o', '--error-file', '/tmp/tmpmod2pyij']
[2022-04-21 21:34:56,665] {standard_task_runner.py:77} INFO - Job 946: Subtask transfer_cso_pers
[2022-04-21 21:34:56,718] {logging_mixin.py:109} INFO - Running <TaskInstance: cso_2295_ipo_2_cso.py.transfer_cso_pers manual__2022-04-21T21:31:39.420323+00:00 [running]> on host 22e04adb6bfa
[2022-04-21 21:34:56,774] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cso_2295_ipo_2_cso.py
AIRFLOW_CTX_TASK_ID=transfer_cso_pers
AIRFLOW_CTX_EXECUTION_DATE=2022-04-21T21:31:39.420323+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-21T21:31:39.420323+00:00
[2022-04-21 21:34:56,787] {base.py:79} INFO - Using connection to: id: postgres_default. Host: postgres, Port: 5432, Schema: ***, Login: ***, Password: ***, extra: {}
[2022-04-21 21:34:56,832] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=cso_2295_ipo_2_cso.py, task_id=transfer_cso_pers, execution_date=20220421T213139, start_date=20220421T213456, end_date=20220421T213456
[2022-04-21 21:34:56,879] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-21 21:34:56,922] {base.py:79} INFO - Using connection to: id: postgres_default. Host: postgres, Port: 5432, Schema: ***, Login: ***, Password: ***, extra: {}
[2022-04-21 21:34:56,925] {dbapi.py:225} INFO - Running statement: UPDATE list_flow_log
                        SET q_source=2,
                        q_target=2, t_end=NOW(), status=2,
                        optional_key='transfer_cso_pers'
                        where id = 85;, parameters: None
[2022-04-21 21:34:56,929] {dbapi.py:233} INFO - Rows affected: 1
[2022-04-21 21:34:56,948] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
